name: GitHub PR checks
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
    types: [opened, reopened, review_request]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file autoDeal/pom.xml
